Adjust the code to work on MIMIC dataset
synthesishealth/chexpert-labeler pull request #1
Opened 2021-10-27 20:37 UTC by Mohammeda4t1qbit

2021-10-28 18:10 UTC, emranmdanas commented on constants/constants.py
> +              "Pulmonary Edema",
Replace Pulmonary Edema by Interstitial fluid, it was suggested by D

2021-10-28 18:11 UTC, emranmdanas commented on constants/constants.py
Pneumothorax is missing

2021-10-28 18:25 UTC, emranmdanas commented on mimic_convert_to_csv.py
> +NLP_csv["report"] = None
we can replace lines 34-40
NLP_csv["report"] = NLP_csv.apply(lambda row: clean_mimic(row["org_report"]), axis=1)
It should be few times faster than using loop.

2021-10-28 18:26 UTC, emranmdanas requested changes
Hi Mohammed, looks OK to me. Thanks for working with the repo. I've few comments. Please also update the phrases from the shared xls file.

2021-10-29 15:28 UTC, EhsanI4t1qbit commented on mimic_convert_to_csv.py
> +NLP_csv["report"] = None
I think the following is also working in here!
`NLP_csv["report"] = NLP_csv["org_report"].apply(lambda x: clean_mimic(x))`

2021-10-29 15:28 UTC, EhsanI4t1qbit commented on label.py
> +                               [i for i in range(max_workers)]), total= max_workers))
Does replacing `[df_split[i] for i in range(max_workers)]` with just `df_split` also work?

2021-10-29 19:48 UTC, Mohammeda4t1qbit commented on constants/constants.py
> +              "Pulmonary Edema",
Done

2021-10-29 19:48 UTC, Mohammeda4t1qbit commented on constants/constants.py
Sone

2021-10-29 19:49 UTC, Mohammeda4t1qbit commented on mimic_convert_to_csv.py
> +NLP_csv["report"] = None
Done , it is super fast now

2021-10-29 19:50 UTC, Mohammeda4t1qbit commented on label.py
> +                               [i for i in range(max_workers)]), total= max_workers))
df_split is a list of small dataframes , so we need to use df_split[i]

2021-10-29 21:50 UTC, EhsanI4t1qbit approved these changes
Good job Mohammed!

2021-11-02 21:27 UTC, emranmdanas commented on phrases/mention/consolidation.txt
> +pna
Pulmonary nodular amyloidosis

2021-11-02 21:34 UTC, emranmdanas commented on phrases/unmention/nodule_mass.txt
> +massive
massive
massengale
cavitated nodul
lymphangitic carcinomatosis
pleural based mass
pleural mass

2021-11-02 21:36 UTC, emranmdanas commented on phrases/mention/pleural_effusion.txt
> +effusion
unmention for pleural_effusion is missing

2021-11-02 21:36 UTC, emranmdanas requested changes
Few comments on phrases.

2021-11-03 18:56 UTC, emranmdanas commented on phrases/mention/consolidation.txt
> +pna
pna --> pulmonary nodular amyloidosis

2021-11-03 18:59 UTC, emranmdanas commented on phrases/unmention/nodule_mass.txt
> +massengale
please check https://docs.google.com/spreadsheets/d/1HiAP8jnbDw3uiMhNLSou2S_4lOSvJoKbpmDfKZVBXUo/edit#gid=2140168161

You;re missing one phrase

2021-11-03 19:00 UTC, emranmdanas commented on phrases/mention/consolidation.txt
> +pna
pna --> pulmonary nodular amyloidosis

2021-11-03 19:34 UTC, emranmdanas approved these changes

2021-11-03 19:36 UTC, merged